### ISSUE TITLE
Tamed wolves Health changing on relog.

### ISSUE THREAD

**Issue by SallyBones** [Wolren/WolfPort#1]
Hi, initially wolves have a health of 40.0, which is changed to 20.0 on relog /S&Q. Not sure what the intended outcome was, but i was having the time of my life with freshly tamed wolves face tanking charged creeper explosions. See:
**Wolf health fresh**
![2024-04-08 09_40_26-Minecraft_ 1 20 1 - Singleplayer](https://github.com/Wolren/WolfPort/assets/166376988/71b6854f-b50c-46d6-8531-d37940c188d8)
**Wolf health Relog**
![2024-04-08 09_39_04-Clipboard](https://github.com/Wolren/WolfPort/assets/166376988/0314bd81-5a65-4214-83ec-5989660f896d)

**Comment by Wolren** [comment]
Fixed, will update today. If you are curious what caused it: I set the health without injecting into setTamed() which worked as long as my code was called after its execution, the thing is that was not always the case. Updated solution injects into the tail of the setTamed() which *should* make it bulletproof
