### ISSUE TITLE
1.0.2-1.20.1 incompatible with woodwalkers (any version)

### ISSUE THREAD

**Issue by kewuon** [Wolren/WolfPort#3]
spawning a wolf with /summon shows "unable to summon entity" message, and trying to spawn one with an egg causes the game to crash. if wolves are already spawned in a world, they simply disappear if walkers is enabled.

the only other mods im using are fabulously optimized mods

[crashlog](https://mclo.gs/dlRgxK7)

**Comment by Wolren** [comment]
Oh alright, it seems to be the woodwalkers problem of reading NBT data from an initialiser modified by a mixin. I will try to find something optimal that avoids using @Overwrite while remaining compatibility in upcoming days. For now you can use 1.0.1 as it seems to be fully cooperative with Woodwalkers
